-- Add Demo Themes to database
INSERT INTO themes (id, title, preview_image, default_color_mode, color_id, font_id, header_id, footer_id, home_landing_id, is_default, enable, created_at) VALUES (3, 'Single Instructor', '/store/landing_builder/landing_4//preview_img.jpg', 'light', 1, 2, 1, 2, 4, 0, 1, 1750090889);
INSERT INTO themes (id, title, preview_image, default_color_mode, color_id, font_id, header_id, footer_id, home_landing_id, is_default, enable, created_at) VALUES (4, 'Organization', '/store/landing_builder/landing_5//preview_img.jpg', 'light', 1, 2, 1, 2, 5, 0, 1, 1750230270);
INSERT INTO themes (id, title, preview_image, default_color_mode, color_id, font_id, header_id, footer_id, home_landing_id, is_default, enable, created_at) VALUES (5, 'Meeting', '/store/landing_builder/landing_6//preview_img.jpg', 'light', 1, 2, 1, 2, 6, 0, 1, 1750513253);
INSERT INTO themes (id, title, preview_image, default_color_mode, color_id, font_id, header_id, footer_id, home_landing_id, is_default, enable, created_at) VALUES (6, 'Instructor', '/store/landing_builder/landing_7//preview_img.jpg', 'light', 1, 2, 1, 2, 7, 0, 1, 1750571508);
INSERT INTO themes (id, title, preview_image, default_color_mode, color_id, font_id, header_id, footer_id, home_landing_id, is_default, enable, created_at) VALUES (7, 'Recruitment', '/store/landing_builder/landing_8//preview_img.jpg', 'light', 1, 2, 1, 2, 8, 0, 1, 1750604459);
INSERT INTO themes (id, title, preview_image, default_color_mode, color_id, font_id, header_id, footer_id, home_landing_id, is_default, enable, created_at) VALUES (8, 'Category', '/store/landing_builder/landing_9//preview_img.jpg', 'light', 1, 2, 1, 2, 9, 0, 1, 1750673976);
INSERT INTO themes (id, title, preview_image, default_color_mode, color_id, font_id, header_id, footer_id, home_landing_id, is_default, enable, created_at) VALUES (9, 'Course', '/store/landing_builder/landing_10//preview_img.jpg', 'light', 1, 2, 1, 2, 10, 0, 1, 1750754252);
INSERT INTO themes (id, title, preview_image, default_color_mode, color_id, font_id, header_id, footer_id, home_landing_id, is_default, enable, created_at) VALUES (10, 'Black Friday', '/store/landing_builder/landing_11//preview_img.jpg', 'dark', 1, 2, 1, 2, 11, 0, 1, 1750785784);
INSERT INTO themes (id, title, preview_image, default_color_mode, color_id, font_id, header_id, footer_id, home_landing_id, is_default, enable, created_at) VALUES (11, 'Learning Path', '/store/landing_builder/landing_12//preview_img.jpg', 'light', 1, 2, 1, 2, 12, 0, 1, 1750945794);
INSERT INTO themes (id, title, preview_image, default_color_mode, color_id, font_id, header_id, footer_id, home_landing_id, is_default, enable, created_at) VALUES (12, 'Universal', '/store/landing_builder/landing_13//preview_img.jpg', 'light', 1, 2, 1, 2, 13, 0, 1, 1751087733);
INSERT INTO themes (id, title, preview_image, default_color_mode, color_id, font_id, header_id, footer_id, home_landing_id, is_default, enable, created_at) VALUES (13, 'School', '/store/landing_builder/landing_15//preview_img.jpg', 'light', 1, 2, 1, 2, 15, 0, 1, 1764140692);
