-- SQL Insert Script for Landing Builder Components
-- This script populates the landing_builder_components table with all 61 components from Theme v2.1

-- First, clear existing data and reset auto-increment
TRUNCATE TABLE `landing_builder_components`;

-- Insert all 61 landing builder components
INSERT INTO `landing_builder_components` (`id`, `name`, `category`, `preview`) VALUES
(1, 'two_columns_hero', 'hero', NULL),
(2, 'full_width_hero', 'hero', NULL),
(3, 'single_instructor_hero', 'hero', NULL),
(4, 'sliding_courses_hero', 'hero', NULL),
(5, 'centered_hero_with_four_images_two_icons', 'hero', NULL),
(6, 'statistics', 'statistics', NULL),
(7, 'featured_courses', 'courses', NULL),
(8, 'links_and_titles_slider_2_rows', 'miscellaneous', NULL),
(9, 'links_and_titles_slider_1_row', 'miscellaneous', NULL),
(10, 'information_cards', 'cards', NULL),
(11, 'trending_categories', 'categories', NULL),
(12, 'newest_courses', 'courses', NULL),
(13, 'best_selling_courses', 'courses', NULL),
(14, 'best_rated_courses', 'courses', NULL),
(15, 'discounted_courses', 'courses', NULL),
(16, 'free_courses', 'courses', NULL),
(17, 'upcoming_courses', 'upcoming_courses', NULL),
(18, 'course_bundles', 'bundles', NULL),
(19, 'store_products', 'store_products', NULL),
(20, 'hybrid_information_section_2_images_check_items_text', 'information', NULL),
(21, 'hybrid_information_section_2_images_text', 'information', NULL),
(22, 'hybrid_information_section_2_images_text_2', 'information', NULL),
(23, 'hybrid_information_section_3_images_text', 'information', NULL),
(24, 'hybrid_information_section_4_images_text', 'information', NULL),
(25, 'company_logos', 'logos', NULL),
(26, 'full_width_bar_cta', 'call_to_action', NULL),
(27, 'faq_6_col', 'faq', NULL),
(28, 'features_4x', 'features', NULL),
(29, 'banners_grid_3_in_different_sizes', 'banners', NULL),
(30, 'meeting_booking_list', 'meeting_booking', NULL),
(31, 'subscription_plans', 'subscription', NULL),
(32, 'single_video_section', 'video', NULL),
(33, 'sliding_testimonials_2_rows', 'testimonials', NULL),
(34, 'cta_card_8_columns', 'call_to_action', NULL),
(35, 'organizations', 'organizations', NULL),
(36, 'instructors', 'instructors', NULL),
(37, 'blog', 'blog_posts', NULL),
(38, 'cta_section_full_width', 'call_to_action', NULL),
(39, 'banner_full_width', 'banners', NULL),
(40, 'banner_3_items_per_row', 'banners', NULL),
(41, 'banner_2_items_per_row', 'banners', NULL),
(42, 'banner_4_items_per_row', 'banners', NULL),
(43, 'boxed_cta_full_width', 'call_to_action', NULL),
(44, 'cta_and_information_hybrid', 'information', NULL),
(45, 'hybrid_information_section_full_width', 'information', NULL),
(46, 'links_and_images_6_items_per_row', 'miscellaneous', NULL),
(47, 'video_and_image_slider_full_width', 'video', NULL),
(48, 'information_card_full_width', 'cards', NULL),
(49, 'information_card_full_width_2', 'cards', NULL),
(50, 'full_width_image_and_video_cta', 'information', NULL),
(51, 'image_information_cards_3x', 'banners', NULL),
(52, 'two_sided_information_images_and_cards', 'information', NULL),
(53, 'linked_images_3x', 'banners', NULL),
(54, 'big_call_to_action_cards_2x', 'call_to_action', NULL),
(55, 'custom_courses_grid', 'courses', NULL),
(56, 'center_text', 'text', NULL),
(57, 'vertical_spacer', 'miscellaneous', NULL),
(58, 'sliding_events', 'cards', NULL),
(59, 'multi_tab_image_video_placeholder', 'video', NULL),
(60, 'multi_tab_courses', 'courses', NULL),
(61, 'countdown_call_to_action', 'call_to_action', NULL),
(62, 'meeting_packages_grid', 'cards', NULL);
